opt_in_rules:
  - empty_count
  - missing_docs
reporter: xcode
warning_threshold: 30
cyclomatic_complexity:
  ignores_case_statements: true
  
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10
  
line_length:
  warning: 120
  error: 240
  ignores_comments: true
  ignores_urls: true
  
custom_rules:
        func_space_rule:
                include: "*.swift"
                regex: '([}]\n[[:blank:]]*func\s\w+(\(.*\))\s[{])'
                name: "Single line space between functions"
                message: "Single line space violation: Expected single whitespace between functions"
                severity: warning
        func_space_rule2:
                include: "*.swift"
                regex: '([}]\n[[:blank:]]*private func\s\w+(\(.*\))\s[{])'
                name: "Single line space between functions"
                message: "Single line space violation: Expected single whitespace between functions"
                severity: warning

